/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppsRouteRouteImport } from './routes/apps/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsListRouteImport } from './routes/apps/list'
import { Route as AppsIdRouteImport } from './routes/apps/$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRouteRoute = AppsRouteRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsListRoute = AppsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppsRouteRoute,
} as any)
const AppsIdRoute = AppsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/apps/$id': typeof AppsIdRoute
  '/apps/list': typeof AppsListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/apps/$id': typeof AppsIdRoute
  '/apps/list': typeof AppsListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/apps/$id': typeof AppsIdRoute
  '/apps/list': typeof AppsListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apps' | '/about' | '/apps/$id' | '/apps/list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apps' | '/about' | '/apps/$id' | '/apps/list'
  id: '__root__' | '/' | '/apps' | '/about' | '/apps/$id' | '/apps/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRouteRoute: typeof AppsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/list': {
      id: '/apps/list'
      path: '/list'
      fullPath: '/apps/list'
      preLoaderRoute: typeof AppsListRouteImport
      parentRoute: typeof AppsRouteRoute
    }
    '/apps/$id': {
      id: '/apps/$id'
      path: '/$id'
      fullPath: '/apps/$id'
      preLoaderRoute: typeof AppsIdRouteImport
      parentRoute: typeof AppsRouteRoute
    }
  }
}

interface AppsRouteRouteChildren {
  AppsIdRoute: typeof AppsIdRoute
  AppsListRoute: typeof AppsListRoute
}

const AppsRouteRouteChildren: AppsRouteRouteChildren = {
  AppsIdRoute: AppsIdRoute,
  AppsListRoute: AppsListRoute,
}

const AppsRouteRouteWithChildren = AppsRouteRoute._addFileChildren(
  AppsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRouteRoute: AppsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
