/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as AppsRouteRouteImport } from './routes/apps/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as SettingsDeploymentRouteImport } from './routes/settings/deployment'
import { Route as SettingsAuthRouteImport } from './routes/settings/auth'
import { Route as AppsHeaderRouteImport } from './routes/apps/header'
import { Route as AppsIdRouteImport } from './routes/apps/$id'
import { Route as SettingsAdminIndexRouteImport } from './routes/settings/admin/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRouteRoute = AppsRouteRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsRouteRoute,
} as any)
const SettingsDeploymentRoute = SettingsDeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAuthRoute = SettingsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AppsHeaderRoute = AppsHeaderRouteImport.update({
  id: '/header',
  path: '/header',
  getParentRoute: () => AppsRouteRoute,
} as any)
const AppsIdRoute = AppsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppsRouteRoute,
} as any)
const SettingsAdminIndexRoute = SettingsAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => SettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apps/$id': typeof AppsIdRoute
  '/apps/header': typeof AppsHeaderRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/deployment': typeof SettingsDeploymentRoute
  '/apps/': typeof AppsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/admin': typeof SettingsAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apps/$id': typeof AppsIdRoute
  '/apps/header': typeof AppsHeaderRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/deployment': typeof SettingsDeploymentRoute
  '/apps': typeof AppsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/admin': typeof SettingsAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apps/$id': typeof AppsIdRoute
  '/apps/header': typeof AppsHeaderRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/deployment': typeof SettingsDeploymentRoute
  '/apps/': typeof AppsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/admin/': typeof SettingsAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/settings'
    | '/about'
    | '/login'
    | '/signup'
    | '/apps/$id'
    | '/apps/header'
    | '/settings/auth'
    | '/settings/deployment'
    | '/apps/'
    | '/settings/'
    | '/settings/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/apps/$id'
    | '/apps/header'
    | '/settings/auth'
    | '/settings/deployment'
    | '/apps'
    | '/settings'
    | '/settings/admin'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/settings'
    | '/about'
    | '/login'
    | '/signup'
    | '/apps/$id'
    | '/apps/header'
    | '/settings/auth'
    | '/settings/deployment'
    | '/apps/'
    | '/settings/'
    | '/settings/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRouteRoute: typeof AppsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/apps/': {
      id: '/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof AppsRouteRoute
    }
    '/settings/deployment': {
      id: '/settings/deployment'
      path: '/deployment'
      fullPath: '/settings/deployment'
      preLoaderRoute: typeof SettingsDeploymentRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/auth': {
      id: '/settings/auth'
      path: '/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof SettingsAuthRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/apps/header': {
      id: '/apps/header'
      path: '/header'
      fullPath: '/apps/header'
      preLoaderRoute: typeof AppsHeaderRouteImport
      parentRoute: typeof AppsRouteRoute
    }
    '/apps/$id': {
      id: '/apps/$id'
      path: '/$id'
      fullPath: '/apps/$id'
      preLoaderRoute: typeof AppsIdRouteImport
      parentRoute: typeof AppsRouteRoute
    }
    '/settings/admin/': {
      id: '/settings/admin/'
      path: '/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof SettingsAdminIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
  }
}

interface AppsRouteRouteChildren {
  AppsIdRoute: typeof AppsIdRoute
  AppsHeaderRoute: typeof AppsHeaderRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

const AppsRouteRouteChildren: AppsRouteRouteChildren = {
  AppsIdRoute: AppsIdRoute,
  AppsHeaderRoute: AppsHeaderRoute,
  AppsIndexRoute: AppsIndexRoute,
}

const AppsRouteRouteWithChildren = AppsRouteRoute._addFileChildren(
  AppsRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAuthRoute: typeof SettingsAuthRoute
  SettingsDeploymentRoute: typeof SettingsDeploymentRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsAdminIndexRoute: typeof SettingsAdminIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAuthRoute: SettingsAuthRoute,
  SettingsDeploymentRoute: SettingsDeploymentRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsAdminIndexRoute: SettingsAdminIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRouteRoute: AppsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
